#include "operations.h"

Operation operations[0x100] = {
	[0x00] = {"NOP", NOP, 0, 0, 0, 0, 0, 0, 1, 4, },
	[0x10] = {"STOP", NOP, 0, 0, 0, 0, 0, 0, 1, 4, }, // TODO implement stop
	[0x76] = {"HALT", HALT, 0, 0, 0, 0, 0, 0, 1, 4, }, 

	// 8 bit loads
	// LD A, R
	[0x7F] = {"LD A, A", LD, REGISTER, REGISTER, A, A, 0, 0, 1, 4},
	[0x78] = {"LD A, B", LD, REGISTER, REGISTER, A, B, 0, 0, 1, 4},
	[0x79] = {"LD A, C", LD, REGISTER, REGISTER, A, C, 0, 0, 1, 4},
	[0x7A] = {"LD A, D", LD, REGISTER, REGISTER, A, D, 0, 0, 1, 4},
	[0x7B] = {"LD A, E", LD, REGISTER, REGISTER, A, E, 0, 0, 1, 4},
	[0x7C] = {"LD A, H", LD, REGISTER, REGISTER, A, H, 0, 0, 1, 4},
	[0x7D] = {"LD A, L", LD, REGISTER, REGISTER, A, L, 0, 0, 1, 4},
	[0x0A] = {"LD A, (BC)", LD, REGISTER, ADDRESS_R16, A, BC, 0, 0, 1, 8},
	[0x7E] = {"LD A, (HL)", LD, REGISTER, ADDRESS_R16, A, HL, 0, 0, 1, 8},
	[0x2A] = {"LD A, (HL+)", LD, REGISTER, ADDRESS_R16, A, HL, 0, INC_R_2, 1, 8},
	[0x3A] = {"LD A, (HL-)", LD, REGISTER, ADDRESS_R16, A, HL, 0, DEC_R_2, 1, 8},
	[0x1A] = {"LD A, (DE)", LD, REGISTER, ADDRESS_R16, A, DE, 0, 0, 1, 8},
	[0xFA] = {"LD A, (u16)", LD, REGISTER, MEM_READ_ADDR, A, U16, 0, 0, 3, 16},
	[0xF0] = {"LD A, (FF00 + u8)", LD, REGISTER, MEM_READ_ADDR_OFFSET, A, U8, 0, 0, 2, 12},
	[0xF2] = {"LD A, (FF00 + C)", LD, REGISTER, ADDRESS_R8_OFFSET, A, C, 0, 0, 1, 8},


	[0x47] = {"LD B, A", LD, REGISTER, REGISTER, B, A, 0, 0, 1, 4},
	[0x40] = {"LD B, B", LD, REGISTER, REGISTER, B, B, 0, 0, 1, 4},
	[0x41] = {"LD B, C", LD, REGISTER, REGISTER, B, C, 0, 0, 1, 4},
	[0x42] = {"LD B, D", LD, REGISTER, REGISTER, B, D, 0, 0, 1, 4},
	[0x43] = {"LD B, E", LD, REGISTER, REGISTER, B, E, 0, 0, 1, 4},
	[0x44] = {"LD B, H", LD, REGISTER, REGISTER, B, H, 0, 0, 1, 4},
	[0x45] = {"LD B, L", LD, REGISTER, REGISTER, B, L, 0, 0, 1, 4},
	[0x46] = {"LD B, (HL)", LD, REGISTER, ADDRESS_R16, B, HL, 0, 0, 1, 8},

	[0x4F] = {"LD C, A", LD, REGISTER, REGISTER, C, A, 0, 0, 1, 4},
	[0x48] = {"LD C, B", LD, REGISTER, REGISTER, C, B, 0, 0, 1, 4},
	[0x49] = {"LD C, C", LD, REGISTER, REGISTER, C, C, 0, 0, 1, 4},
	[0x4A] = {"LD C, D", LD, REGISTER, REGISTER, C, D, 0, 0, 1, 4},
	[0x4B] = {"LD C, E", LD, REGISTER, REGISTER, C, E, 0, 0, 1, 4},
	[0x4C] = {"LD C, H", LD, REGISTER, REGISTER, C, H, 0, 0, 1, 4},
	[0x4D] = {"LD C, L", LD, REGISTER, REGISTER, C, L, 0, 0, 1, 4},
	[0x4E] = {"LD C, (HL)", LD, REGISTER, ADDRESS_R16, C, HL, 0, 0, 1, 8},

	[0x57] = {"LD D, A", LD, REGISTER, REGISTER, D, A, 0, 0, 1, 4},
	[0x50] = {"LD D, B", LD, REGISTER, REGISTER, D, B, 0, 0, 1, 4},
	[0x51] = {"LD D, C", LD, REGISTER, REGISTER, D, C, 0, 0, 1, 4},
	[0x52] = {"LD D, D", LD, REGISTER, REGISTER, D, D, 0, 0, 1, 4},
	[0x53] = {"LD D, E", LD, REGISTER, REGISTER, D, E, 0, 0, 1, 4},
	[0x54] = {"LD D, H", LD, REGISTER, REGISTER, D, H, 0, 0, 1, 4},
	[0x55] = {"LD D, L", LD, REGISTER, REGISTER, D, L, 0, 0, 1, 4},
	[0x56] = {"LD D, (HL)", LD, REGISTER, ADDRESS_R16, D, HL, 0, 0, 1, 8},

	[0x5F] = {"LD E, A", LD, REGISTER, REGISTER, E, A, 0, 0, 1, 4},
	[0x58] = {"LD E, B", LD, REGISTER, REGISTER, E, B, 0, 0, 1, 4},
	[0x59] = {"LD E, C", LD, REGISTER, REGISTER, E, C, 0, 0, 1, 4},
	[0x5A] = {"LD E, D", LD, REGISTER, REGISTER, E, D, 0, 0, 1, 4},
	[0x5B] = {"LD E, E", LD, REGISTER, REGISTER, E, E, 0, 0, 1, 4},
	[0x5C] = {"LD E, H", LD, REGISTER, REGISTER, E, H, 0, 0, 1, 4},
	[0x5D] = {"LD E, L", LD, REGISTER, REGISTER, E, L, 0, 0, 1, 4},
	[0x5E] = {"LD E, (HL)", LD, REGISTER, ADDRESS_R16, E, HL, 0, 0, 1, 8},

	[0x67] = {"LD H, A", LD, REGISTER, REGISTER, H, A, 0, 0, 1, 4},
	[0x60] = {"LD H, B", LD, REGISTER, REGISTER, H, B, 0, 0, 1, 4},
	[0x61] = {"LD H, C", LD, REGISTER, REGISTER, H, C, 0, 0, 1, 4},
	[0x62] = {"LD H, D", LD, REGISTER, REGISTER, H, D, 0, 0, 1, 4},
	[0x63] = {"LD H, E", LD, REGISTER, REGISTER, H, E, 0, 0, 1, 4},
	[0x64] = {"LD H, H", LD, REGISTER, REGISTER, H, H, 0, 0, 1, 4},
	[0x65] = {"LD H, L", LD, REGISTER, REGISTER, H, L, 0, 0, 1, 4},
	[0x66] = {"LD H, (HL)", LD, REGISTER, ADDRESS_R16, H, HL, 0, 0, 1, 8},

	[0x6F] = {"LD L, A", LD, REGISTER, REGISTER, L, A, 0, 0, 1, 4},
	[0x68] = {"LD L, B", LD, REGISTER, REGISTER, L, B, 0, 0, 1, 4},
	[0x69] = {"LD L, C", LD, REGISTER, REGISTER, L, C, 0, 0, 1, 4},
	[0x6A] = {"LD L, D", LD, REGISTER, REGISTER, L, D, 0, 0, 1, 4},
	[0x6B] = {"LD L, E", LD, REGISTER, REGISTER, L, E, 0, 0, 1, 4},
	[0x6C] = {"LD L, H", LD, REGISTER, REGISTER, L, H, 0, 0, 1, 4},
	[0x6D] = {"LD L, L", LD, REGISTER, REGISTER, L, L, 0, 0, 1, 4},
	[0x6E] = {"LD L, (HL)", LD, REGISTER, ADDRESS_R16, L, HL, 0, 0, 1, 8},

	[0xE2] = {"LD (FF00 + C), A", LD, ADDRESS_R8_OFFSET, REGISTER, C, A, 0, 0, 1, 8},
	// 
	// 
	// LD X, u8
	[0x3E] = {"LD A, u8", LD, REGISTER, MEM_READ, A, U8, 0, 0, 2, 8},
	[0x06] = {"LD B, u8", LD, REGISTER, MEM_READ, B, U8, 0, 0, 2, 8},
	[0x0E] = {"LD C, u8", LD, REGISTER, MEM_READ, C, U8, 0, 0, 2, 8},
	[0x16] = {"LD D, u8", LD, REGISTER, MEM_READ, D, U8, 0, 0, 2, 8},
	[0x1E] = {"LD E, u8", LD, REGISTER, MEM_READ, E, U8, 0, 0, 2, 8},
	[0x26] = {"LD H, u8", LD, REGISTER, MEM_READ, H, U8, 0, 0, 2, 8},
	[0x2E] = {"LD L, u8", LD, REGISTER, MEM_READ, L, U8, 0, 0, 2, 8},

	[0xE0] = {"LD (FF00 + u8), A", LD, MEM_READ_ADDR_OFFSET, REGISTER, U8, A, 0, 0, 2, 12},

	// LD (HL)
	[0x02] = {"LD (BC), A", LD, ADDRESS_R16, REGISTER, BC, A, 0, SECONDARY_NONE, 1, 8 },
	[0x12] = {"LD (DE), A", LD, ADDRESS_R16, REGISTER, DE, A, 0, SECONDARY_NONE, 1, 8 },

	[0x77] = {"LD (HL), A", LD, ADDRESS_R16, REGISTER, HL, A, 0, SECONDARY_NONE, 1, 8 },
	[0x32] = {"LD (HL-), A", LD, ADDRESS_R16, REGISTER, HL, A, 0, DEC_R_1, 1, 8 },
	[0x22] = {"LD (HL+), A", LD, ADDRESS_R16, REGISTER, HL, A, 0, INC_R_1, 1, 8 },
	[0x70] = {"LD (HL), B", LD, ADDRESS_R16, REGISTER, HL, B, 0, SECONDARY_NONE, 1, 8 },
	[0x71] = {"LD (HL), C", LD, ADDRESS_R16, REGISTER, HL, C, 0, SECONDARY_NONE, 1, 8 },
	[0x72] = {"LD (HL), D", LD, ADDRESS_R16, REGISTER, HL, D, 0, SECONDARY_NONE, 1, 8 },
	[0x73] = {"LD (HL), E", LD, ADDRESS_R16, REGISTER, HL, E, 0, SECONDARY_NONE, 1, 8 },
	[0x74] = {"LD (HL), H", LD, ADDRESS_R16, REGISTER, HL, H, 0, SECONDARY_NONE, 1, 8 },
	[0x75] = {"LD (HL), L", LD, ADDRESS_R16, REGISTER, HL, L, 0, SECONDARY_NONE, 1, 8 },
	[0x36] = {"LD (HL), u8", LD, ADDRESS_R16, MEM_READ, HL, U8, 0, 0, 2, 12},

	// 16 bit loads

	[0xEA] = {"LD (u16), A", LD, MEM_READ_ADDR, REGISTER, U16, A, 0, 0, 3, 16},
	[0x08] = {"LD (u16), SP", LD, MEM_READ_ADDR, REGISTER16, U16, SP, 0, 0, 3, 20},

	[0x01] = {"LD BC, u16", LD, REGISTER16, MEM_READ16, BC, U16, 0, 0, 3, 12},
	[0x11] = {"LD DE, u16", LD, REGISTER16, MEM_READ16, DE, U16, 0, 0, 3, 12},

	// LD SP
	[0x31] = {"LD SP, u16", LD, REGISTER16, MEM_READ16, SP, U16, 0, 0, 3, 12, },
	[0xF9] = {"LD SP, HL", LD, REGISTER16, REGISTER16, SP, HL, 0, 0, 1, 8, },

	// LD HL
[0x21] = { "LD HL, u16", LD, REGISTER16, MEM_READ16, HL, U16, 0, 0, 3, 12, },
[0xF8] = { "LD HL, SP + i8", LD, REGISTER16, REGISTER16, HL, SP_ADD_I8, 0, 0, 2, 12, {RESET, RESET, DEPENDENT, DEPENDENT} },

// ALU
// INC r8
[0x3C] = { "INC A", INC, REGISTER, ADDR_MODE_NONE, A, OPERAND_NONE, 0, 0, 1, 4, {DEPENDENT, RESET, DEPENDENT, _IGNORE} },
[0x04] = { "INC B", INC, REGISTER, ADDR_MODE_NONE, B, OPERAND_NONE, 0, 0, 1, 4, {DEPENDENT, RESET, DEPENDENT, _IGNORE} },
[0x0C] = { "INC C", INC, REGISTER, ADDR_MODE_NONE, C, OPERAND_NONE, 0, 0, 1, 4, {DEPENDENT, RESET, DEPENDENT, _IGNORE} },
[0x14] = { "INC D", INC, REGISTER, ADDR_MODE_NONE, D, OPERAND_NONE, 0, 0, 1, 4, {DEPENDENT, RESET, DEPENDENT, _IGNORE} },
[0x1C] = { "INC E", INC, REGISTER, ADDR_MODE_NONE, E, OPERAND_NONE, 0, 0, 1, 4, {DEPENDENT, RESET, DEPENDENT, _IGNORE} },
[0x24] = { "INC H", INC, REGISTER, ADDR_MODE_NONE, H, OPERAND_NONE, 0, 0, 1, 4, {DEPENDENT, RESET, DEPENDENT, _IGNORE} },
[0x2C] = { "INC L", INC, REGISTER, ADDR_MODE_NONE, L, OPERAND_NONE, 0, 0, 1, 4, {DEPENDENT, RESET, DEPENDENT, _IGNORE} },
[0x34] = { "INC (HL)", INC, ADDRESS_R16, ADDR_MODE_NONE, HL, OPERAND_NONE, 0, 0, 1, 12, {DEPENDENT, RESET, DEPENDENT, _IGNORE} },

// DEC R8
[0x3D] = { "DEC A", DEC, REGISTER, ADDR_MODE_NONE, A, OPERAND_NONE, 0, 0, 1, 4, {DEPENDENT, SET, DEPENDENT, _IGNORE} },
[0x05] = { "DEC B", DEC, REGISTER, ADDR_MODE_NONE, B, OPERAND_NONE, 0, 0, 1, 4, {DEPENDENT, SET, DEPENDENT, _IGNORE} },
[0x0D] = { "DEC C", DEC, REGISTER, ADDR_MODE_NONE, C, OPERAND_NONE, 0, 0, 1, 4, {DEPENDENT, SET, DEPENDENT, _IGNORE} },
[0x15] = { "DEC D", DEC, REGISTER, ADDR_MODE_NONE, D, OPERAND_NONE, 0, 0, 1, 4, {DEPENDENT, SET, DEPENDENT, _IGNORE} },
[0x1D] = { "DEC E", DEC, REGISTER, ADDR_MODE_NONE, E, OPERAND_NONE, 0, 0, 1, 4, {DEPENDENT, SET, DEPENDENT, _IGNORE} },
[0x25] = { "DEC H", DEC, REGISTER, ADDR_MODE_NONE, H, OPERAND_NONE, 0, 0, 1, 4, {DEPENDENT, SET, DEPENDENT, _IGNORE} },
[0x2D] = { "DEC L", DEC, REGISTER, ADDR_MODE_NONE, L, OPERAND_NONE, 0, 0, 1, 4, {DEPENDENT, SET, DEPENDENT, _IGNORE} },

[0x35] = { "DEC (HL)", DEC, ADDRESS_R16, ADDR_MODE_NONE, HL, OPERAND_NONE, 0, 0, 1, 12, {DEPENDENT, SET, DEPENDENT, _IGNORE} },

// ADD
[0x87] = { "ADD A, A", ADD, REGISTER, REGISTER, A, A, 0, 0, 1, 4, {DEPENDENT, RESET, DEPENDENT, DEPENDENT} },
[0x80] = { "ADD A, B", ADD, REGISTER, REGISTER, A, B, 0, 0, 1, 4, {DEPENDENT, RESET, DEPENDENT, DEPENDENT} },
[0x81] = { "ADD A, C", ADD, REGISTER, REGISTER, A, C, 0, 0, 1, 4, {DEPENDENT, RESET, DEPENDENT, DEPENDENT} },
[0x82] = { "ADD A, D", ADD, REGISTER, REGISTER, A, D, 0, 0, 1, 4, {DEPENDENT, RESET, DEPENDENT, DEPENDENT} },
[0x83] = { "ADD A, E", ADD, REGISTER, REGISTER, A, E, 0, 0, 1, 4, {DEPENDENT, RESET, DEPENDENT, DEPENDENT} },
[0x84] = { "ADD A, H", ADD, REGISTER, REGISTER, A, H, 0, 0, 1, 4, {DEPENDENT, RESET, DEPENDENT, DEPENDENT} },
[0x85] = { "ADD A, L", ADD, REGISTER, REGISTER, A, L, 0, 0, 1, 4, {DEPENDENT, RESET, DEPENDENT, DEPENDENT} },
[0x86] = { "ADD A, (HL)", ADD, REGISTER, ADDRESS_R16, A, HL, 0, 0, 1, 8, {DEPENDENT, RESET, DEPENDENT, DEPENDENT} },
[0xC6] = { "ADD A, u8", ADD, REGISTER, MEM_READ, A, U8, 0, 0, 2, 8, {DEPENDENT, RESET, DEPENDENT, DEPENDENT} },

[0x8F] = { "ADC A, A", ADC, REGISTER, REGISTER, A, A, 0, 0, 1, 4, {DEPENDENT, RESET, DEPENDENT, DEPENDENT} },
[0x88] = { "ADC A, B", ADC, REGISTER, REGISTER, A, B, 0, 0, 1, 4, {DEPENDENT, RESET, DEPENDENT, DEPENDENT} },
[0x89] = { "ADC A, C", ADC, REGISTER, REGISTER, A, C, 0, 0, 1, 4, {DEPENDENT, RESET, DEPENDENT, DEPENDENT} },
[0x8A] = { "ADC A, D", ADC, REGISTER, REGISTER, A, D, 0, 0, 1, 4, {DEPENDENT, RESET, DEPENDENT, DEPENDENT} },
[0x8B] = { "ADC A, E", ADC, REGISTER, REGISTER, A, E, 0, 0, 1, 4, {DEPENDENT, RESET, DEPENDENT, DEPENDENT} },
[0x8C] = { "ADC A, H", ADC, REGISTER, REGISTER, A, H, 0, 0, 1, 4, {DEPENDENT, RESET, DEPENDENT, DEPENDENT} },
[0x8D] = { "ADC A, L", ADC, REGISTER, REGISTER, A, L, 0, 0, 1, 4, {DEPENDENT, RESET, DEPENDENT, DEPENDENT} },
[0x8E] = { "ADC A, (HL)", ADC, REGISTER, ADDRESS_R16, A, HL, 0, 0, 1, 8, {DEPENDENT, RESET, DEPENDENT, DEPENDENT} },
[0xCE] = { "ADC A, u8", ADC, REGISTER, MEM_READ, A, U8, 0, 0, 2, 8, {DEPENDENT, RESET, DEPENDENT, DEPENDENT} },
// SUB
[0x97] = { "SUB A, A", SUB, REGISTER, REGISTER, A, A, 0, 0, 1, 4, {DEPENDENT, SET, DEPENDENT, DEPENDENT} },
[0x90] = { "SUB A, B", SUB, REGISTER, REGISTER, A, B, 0, 0, 1, 4, {DEPENDENT, SET, DEPENDENT, DEPENDENT} },
[0x91] = { "SUB A, C", SUB, REGISTER, REGISTER, A, C, 0, 0, 1, 4, {DEPENDENT, SET, DEPENDENT, DEPENDENT} },
[0x92] = { "SUB A, D", SUB, REGISTER, REGISTER, A, D, 0, 0, 1, 4, {DEPENDENT, SET, DEPENDENT, DEPENDENT} },
[0x93] = { "SUB A, E", SUB, REGISTER, REGISTER, A, E, 0, 0, 1, 4, {DEPENDENT, SET, DEPENDENT, DEPENDENT} },
[0x94] = { "SUB A, H", SUB, REGISTER, REGISTER, A, H, 0, 0, 1, 4, {DEPENDENT, SET, DEPENDENT, DEPENDENT} },
[0x95] = { "SUB A, L", SUB, REGISTER, REGISTER, A, L, 0, 0, 1, 4, {DEPENDENT, SET, DEPENDENT, DEPENDENT} },
[0x96] = { "SUB A, (HL)", SUB, REGISTER, ADDRESS_R16, A, HL, 0, 0, 2, 8, {DEPENDENT, SET, DEPENDENT, DEPENDENT} },
[0xD6] = { "SUB A, u8", SUB, REGISTER, MEM_READ, A, U8, 0, 0, 2, 8, {DEPENDENT, SET, DEPENDENT, DEPENDENT} },

[0x9F] = { "SBC A, A", SBC, REGISTER, REGISTER, A, A, 0, 0, 1, 4, {DEPENDENT, SET, DEPENDENT, DEPENDENT} },
[0x98] = { "SBC A, B", SBC, REGISTER, REGISTER, A, B, 0, 0, 1, 4, {DEPENDENT, SET, DEPENDENT, DEPENDENT} },
[0x99] = { "SBC A, C", SBC, REGISTER, REGISTER, A, C, 0, 0, 1, 4, {DEPENDENT, SET, DEPENDENT, DEPENDENT}},
[0x9A] = { "SBC A, D", SBC, REGISTER, REGISTER, A, D, 0, 0, 1, 4, {DEPENDENT, SET, DEPENDENT, DEPENDENT} },
[0x9B] = { "SBC A, E", SBC, REGISTER, REGISTER, A, E, 0, 0, 1, 4, {DEPENDENT, SET, DEPENDENT, DEPENDENT} },
[0x9C] = { "SBC A, H", SBC, REGISTER, REGISTER, A, H, 0, 0, 1, 4, {DEPENDENT, SET, DEPENDENT, DEPENDENT}},
[0x9D] = { "SBC A, L", SBC, REGISTER, REGISTER, A, L, 0, 0, 1, 4, {DEPENDENT, SET, DEPENDENT, DEPENDENT}},
[0x9E] = { "SBC A, (HL)", SBC, REGISTER, ADDRESS_R16, A, HL, 0, 0, 2, 8, {DEPENDENT, SET, DEPENDENT, DEPENDENT} },
[0xDE] = { "SBC A, u8", SBC, REGISTER, MEM_READ, A, U8, 0, 0, 2, 8, {DEPENDENT, SET, DEPENDENT, DEPENDENT}},

// CP
[0xBF] = { "CP A, A", CP, REGISTER, REGISTER, A, A, 0, 0, 1, 4, {DEPENDENT, SET, DEPENDENT, DEPENDENT} },
[0xB8] = { "CP A, B", CP, REGISTER, REGISTER, A, B, 0, 0, 1, 4, {DEPENDENT, SET, DEPENDENT, DEPENDENT} },
[0xB9] = { "CP A, C", CP, REGISTER, REGISTER, A, C, 0, 0, 1, 4, {DEPENDENT, SET, DEPENDENT, DEPENDENT} },
[0xBA] = { "CP A, D", CP, REGISTER, REGISTER, A, D, 0, 0, 1, 4, {DEPENDENT, SET, DEPENDENT, DEPENDENT} },
[0xBB] = { "CP A, E", CP, REGISTER, REGISTER, A, E, 0, 0, 1, 4, {DEPENDENT, SET, DEPENDENT, DEPENDENT} },
[0xBC] = { "CP A, H", CP, REGISTER, REGISTER, A, H, 0, 0, 1, 4, {DEPENDENT, SET, DEPENDENT, DEPENDENT} },
[0xBD] = { "CP A, L", CP, REGISTER, REGISTER, A, L, 0, 0, 1, 4, {DEPENDENT, SET, DEPENDENT, DEPENDENT} },
[0xBE] = { "CP A, (HL)", CP, REGISTER, ADDRESS_R16, A, HL, 0, 0, 1, 8, {DEPENDENT, SET, DEPENDENT, DEPENDENT} },
[0xFE] = { "CP A, u8", CP, REGISTER, MEM_READ, A, U8, 0, 0, 2, 8, {DEPENDENT, SET, DEPENDENT, DEPENDENT} },

//INC r16
[0x03] = { "INC BC", INC, REGISTER16, ADDR_MODE_NONE, BC, OPERAND_NONE, 0, 0, 1, 8 },
[0x13] = { "INC DE", INC, REGISTER16, ADDR_MODE_NONE, DE, OPERAND_NONE, 0, 0, 1, 8 },
[0x23] = { "INC HL", INC, REGISTER16, ADDR_MODE_NONE, HL, OPERAND_NONE, 0, 0, 1, 8 },
[0x33] = { "INC SP", INC, REGISTER16, ADDR_MODE_NONE, SP, OPERAND_NONE, 0, 0, 1, 8 },

// DEC r16
[0x0B] = { "DEC BC", DEC, REGISTER16, ADDR_MODE_NONE, BC, OPERAND_NONE, 0, 0, 1, 8 },
[0x1B] = { "DEC DE", DEC, REGISTER16, ADDR_MODE_NONE, DE, OPERAND_NONE, 0, 0, 1, 8 },
[0x2B] = { "DEC HL", DEC, REGISTER16, ADDR_MODE_NONE, HL, OPERAND_NONE, 0, 0, 1, 8 },
[0x3B] = { "DEC SP", DEC, REGISTER16, ADDR_MODE_NONE, SP, OPERAND_NONE, 0, 0, 1, 8 },

[0x09] = { "ADD HL, BC", ADD, REGISTER16, REGISTER16, HL, BC, 0, 0, 1, 8, {_IGNORE, RESET, DEPENDENT, DEPENDENT} },
[0x19] = { "ADD HL, DE", ADD, REGISTER16, REGISTER16, HL, DE, 0, 0, 1, 8, {_IGNORE, RESET, DEPENDENT, DEPENDENT} },
[0x29] = { "ADD HL, HL", ADD, REGISTER16, REGISTER16, HL, HL, 0, 0, 1, 8, {_IGNORE, RESET, DEPENDENT, DEPENDENT} },
[0x39] = { "ADD HL, SP", ADD, REGISTER16, REGISTER16, HL, SP, 0, 0, 1, 8, {_IGNORE, RESET, DEPENDENT, DEPENDENT} },

[0xE8] = { "ADD SP, i8", ADD, REGISTER16, MEM_READ, SP, I8, 0, 0, 2, 16, {RESET, RESET, DEPENDENT, DEPENDENT} }, // TRUST ME THIS IS THE EASIEST WAY


// AND
[0xA7] = { "AND A, A", AND, REGISTER, REGISTER, A, A, 0, 0, 1, 4, {DEPENDENT, RESET, SET, RESET} },
[0xA0] = { "AND A, B", AND, REGISTER, REGISTER, A, B, 0, 0, 1, 4, {DEPENDENT, RESET, SET, RESET} },
[0xA1] = { "AND A, C", AND, REGISTER, REGISTER, A, C, 0, 0, 1, 4, {DEPENDENT, RESET, SET, RESET} },
[0xA2] = { "AND A, D", AND, REGISTER, REGISTER, A, D, 0, 0, 1, 4, {DEPENDENT, RESET, SET, RESET} },
[0xA3] = { "AND A, E", AND, REGISTER, REGISTER, A, E, 0, 0, 1, 4, {DEPENDENT, RESET, SET, RESET} },
[0xA4] = { "AND A, H", AND, REGISTER, REGISTER, A, H, 0, 0, 1, 4, {DEPENDENT, RESET, SET, RESET} },
[0xA5] = { "AND A, L", AND, REGISTER, REGISTER, A, L, 0, 0, 1, 4, {DEPENDENT, RESET, SET, RESET} },
[0xA6] = { "AND A, (HL)", AND, REGISTER, ADDRESS_R16, A, HL, 0, 0, 1, 8, {DEPENDENT, RESET, SET, RESET} },
[0xE6] = { "AND A, u8", AND, REGISTER, MEM_READ, A, U8, 0, 0, 2, 8, {DEPENDENT, RESET, SET, RESET} },

// OR
[0xB7] = { "OR A, A", OR, REGISTER, REGISTER, A, A, 0, 0, 1, 4, {DEPENDENT, RESET, RESET, RESET} },
[0xB0] = { "OR A, B", OR, REGISTER, REGISTER, A, B, 0, 0, 1, 4, {DEPENDENT, RESET, RESET, RESET} },
[0xB1] = { "OR A, C", OR, REGISTER, REGISTER, A, C, 0, 0, 1, 4, {DEPENDENT, RESET, RESET, RESET} },
[0xB2] = { "OR A, D", OR, REGISTER, REGISTER, A, D, 0, 0, 1, 4, {DEPENDENT, RESET, RESET, RESET} },
[0xB3] = { "OR A, E", OR, REGISTER, REGISTER, A, E, 0, 0, 1, 4, {DEPENDENT, RESET, RESET, RESET} },
[0xB4] = { "OR A, H", OR, REGISTER, REGISTER, A, H, 0, 0, 1, 4, {DEPENDENT, RESET, RESET, RESET} },
[0xB5] = { "OR A, L", OR, REGISTER, REGISTER, A, L, 0, 0, 1, 4, {DEPENDENT, RESET, RESET, RESET} },
[0xB6] = { "OR A, (HL)", OR, REGISTER, ADDRESS_R16, A, HL, 0, 0, 1, 8, {DEPENDENT, RESET, RESET, RESET} },
[0xF6] = { "OR A, U8", OR, REGISTER, MEM_READ, A, U8, 0, 0, 1, 4, {DEPENDENT, RESET, RESET, RESET} },
// XOR
[0xAF] = { "XOR A, A", XOR, REGISTER, REGISTER, A, A, 0, 0, 1, 4, {DEPENDENT, RESET, RESET, RESET} },
[0xA8] = { "XOR A, B", XOR, REGISTER, REGISTER, A, B, 0, 0, 1, 4, {DEPENDENT, RESET, RESET, RESET} },
[0xA9] = { "XOR A, C", XOR, REGISTER, REGISTER, A, C, 0, 0, 1, 4, {DEPENDENT, RESET, RESET, RESET} },
[0xAA] = { "XOR A, D", XOR, REGISTER, REGISTER, A, D, 0, 0, 1, 4, {DEPENDENT, RESET, RESET, RESET} },
[0xAB] = { "XOR A, E", XOR, REGISTER, REGISTER, A, E, 0, 0, 1, 4, {DEPENDENT, RESET, RESET, RESET} },
[0xAC] = { "XOR A, H", XOR, REGISTER, REGISTER, A, H, 0, 0, 1, 4, {DEPENDENT, RESET, RESET, RESET} },
[0xAD] = { "XOR A, L", XOR, REGISTER, REGISTER, A, L, 0, 0, 1, 4, {DEPENDENT, RESET, RESET, RESET} },
[0xAE] = { "XOR A, (HL)", XOR, REGISTER, ADDRESS_R16, A, HL, 0, 0, 1, 8, {DEPENDENT, RESET, RESET, RESET} },
[0xEE] = { "XOR A, u8", XOR, REGISTER, MEM_READ, A, U8, 0, 0, 2, 8, {DEPENDENT, RESET, RESET, RESET} },

[0x2F] = { "CPL A", CPL, REGISTER, ADDR_MODE_NONE, A, OPERAND_NONE, 0, 0, 1, 4, {_IGNORE, SET, SET, _IGNORE} },

// PUSH
[0xF5] = { "PUSH AF", PUSH, ADDR_MODE_NONE, REGISTER16, OPERAND_NONE, AF, 0, 0, 1, 16 },
[0xC5] = { "PUSH BC", PUSH, ADDR_MODE_NONE, REGISTER16, OPERAND_NONE, BC, 0, 0, 1, 16 },
[0xD5] = { "PUSH DE", PUSH, ADDR_MODE_NONE, REGISTER16, OPERAND_NONE, DE, 0, 0, 1, 16 },
[0xE5] = { "PUSH HL", PUSH, ADDR_MODE_NONE, REGISTER16, OPERAND_NONE, HL, 0, 0, 1, 16 },

// POP
[0xC1] = { "POP BC", POP, REGISTER16, ADDR_MODE_NONE, BC, OPERAND_NONE, 0, 0, 1, 12 },
[0xD1] = { "POP DE", POP, REGISTER16, ADDR_MODE_NONE, DE, OPERAND_NONE, 0, 0, 1, 12 },
[0xE1] = { "POP HL", POP, REGISTER16, ADDR_MODE_NONE, HL, OPERAND_NONE, 0, 0, 1, 12 },
[0xF1] = { "POP AF", POP, REGISTER16, ADDR_MODE_NONE, AF, OPERAND_NONE, 0, 0, 1, 12 },


// JUMPS

[0x18] = { "JR, i8", JP, ADDR_MODE_NONE, MEM_READ, OPERAND_NONE, I8, CONDITION_NONE, SECONDARY_NONE, 2, 12 },
[0x20] = { "JR NZ, i8", JP, ADDR_MODE_NONE, MEM_READ, OPERAND_NONE, I8, CONDITION_NZ, ADD_T_4, 2, 8 },
[0x28] = { "JR Z, i8", JP, ADDR_MODE_NONE, MEM_READ, OPERAND_NONE, I8, CONDITION_Z, ADD_T_4, 2, 8 },
[0x38] = { "JR C, i8", JP, ADDR_MODE_NONE, MEM_READ, OPERAND_NONE, I8, CONDITION_C, ADD_T_4, 2, 8 },
[0x30] = { "JR NC, i8", JP, ADDR_MODE_NONE, MEM_READ, OPERAND_NONE, I8, CONDITION_NC, ADD_T_4, 2, 8 },

[0xC3] = { "JP u16", JP, ADDR_MODE_NONE, MEM_READ16, OPERAND_NONE, U16, CONDITION_NONE, SECONDARY_NONE, 3, 16 },
[0xC2] = { "JP NZ u16", JP, ADDR_MODE_NONE, MEM_READ16, OPERAND_NONE, U16, CONDITION_NZ, ADD_T_4, 3, 12 },
[0xCA] = { "JP Z u16", JP, ADDR_MODE_NONE, MEM_READ16, OPERAND_NONE, U16, CONDITION_Z, ADD_T_4, 3, 12 },
[0xD2] = { "JP NC u16", JP, ADDR_MODE_NONE, MEM_READ16, OPERAND_NONE, U16, CONDITION_NC, ADD_T_4, 3, 12 },
[0xDA] = { "JP C u16", JP, ADDR_MODE_NONE, MEM_READ16, OPERAND_NONE, U16, CONDITION_C, ADD_T_4, 3, 12 },
[0xE9] = { "JP HL", JP, ADDR_MODE_NONE, REGISTER16, OPERAND_NONE, HL, CONDITION_NONE, SECONDARY_NONE, 1, 4 },

// CALLS
[0xCD] = { "CALL u16", CALL, ADDR_MODE_NONE, MEM_READ16, OPERAND_NONE, U16, CONDITION_NONE, SECONDARY_NONE, 3, 24 },
[0xCC] = { "CALL Z u16", CALL, ADDR_MODE_NONE, MEM_READ16, OPERAND_NONE, U16, CONDITION_Z, ADD_T_12, 3, 12 },
[0xC4] = { "CALL NZ u16", CALL, ADDR_MODE_NONE, MEM_READ16, OPERAND_NONE, U16, CONDITION_NZ, ADD_T_12, 3, 12 },
[0xDC] = { "CALL C u16", CALL, ADDR_MODE_NONE, MEM_READ16, OPERAND_NONE, U16, CONDITION_C, ADD_T_12, 3, 12 },
[0xD4] = { "CALL NC u16", CALL, ADDR_MODE_NONE, MEM_READ16, OPERAND_NONE, U16, CONDITION_NC, ADD_T_12, 3, 12 },

// RST (store rst jump in dest)
[0xC7] = { "RST 00", RST, ADDR_MODE_NONE, ADDR_MODE_NONE, 0x0, OPERAND_NONE, CONDITION_NONE, SECONDARY_NONE, 1, 16 },
[0xCF] = { "RST 08", RST, ADDR_MODE_NONE, ADDR_MODE_NONE, 0x8, OPERAND_NONE, CONDITION_NONE, SECONDARY_NONE, 1, 16 },
[0xD7] = { "RST 10", RST, ADDR_MODE_NONE, ADDR_MODE_NONE, 0x10, OPERAND_NONE, CONDITION_NONE, SECONDARY_NONE, 1, 16 },
[0xDF] = { "RST 18", RST, ADDR_MODE_NONE, ADDR_MODE_NONE, 0x18, OPERAND_NONE, CONDITION_NONE, SECONDARY_NONE, 1, 16 },
[0xE7] = { "RST 20", RST, ADDR_MODE_NONE, ADDR_MODE_NONE, 0x20, OPERAND_NONE, CONDITION_NONE, SECONDARY_NONE, 1, 16 },
[0xEF] = { "RST 28", RST, ADDR_MODE_NONE, ADDR_MODE_NONE, 0x28, OPERAND_NONE, CONDITION_NONE, SECONDARY_NONE, 1, 16 },
[0xF7] = { "RST 30", RST, ADDR_MODE_NONE, ADDR_MODE_NONE, 0x30, OPERAND_NONE, CONDITION_NONE, SECONDARY_NONE, 1, 16 },
[0xFF] = { "RST 38", RST, ADDR_MODE_NONE, ADDR_MODE_NONE, 0x38, OPERAND_NONE, CONDITION_NONE, SECONDARY_NONE, 1, 16 },

// RET
[0xC9] = { "RET", RET, ADDR_MODE_NONE, ADDR_MODE_NONE, OPERAND_NONE, OPERAND_NONE, CONDITION_NONE, SECONDARY_NONE, 1, 16},
[0xC8] = { "RET Z", RET, ADDR_MODE_NONE, ADDR_MODE_NONE, OPERAND_NONE, OPERAND_NONE, CONDITION_Z, ADD_T_12, 1, 8},
[0xC0] = { "RET NZ", RET, ADDR_MODE_NONE, ADDR_MODE_NONE, OPERAND_NONE, OPERAND_NONE, CONDITION_NZ, ADD_T_12, 1, 8},
[0xD8] = { "RET C", RET, ADDR_MODE_NONE, ADDR_MODE_NONE, OPERAND_NONE, OPERAND_NONE, CONDITION_C, ADD_T_12, 1, 8},
[0xD0] = { "RET NC", RET, ADDR_MODE_NONE, ADDR_MODE_NONE, OPERAND_NONE, OPERAND_NONE, CONDITION_NC, ADD_T_12, 1, 8},

[0xD9] = { "RETI", RETI, ADDR_MODE_NONE, ADDR_MODE_NONE, OPERAND_NONE, OPERAND_NONE, CONDITION_NONE, SECONDARY_NONE, 1, 16},
// MISC
[0xCB] = { "PREFIX CB", CB, MEM_READ, ADDR_MODE_NONE, OPERAND_NONE, OPERAND_NONE, 0, 0, 0, 0},
[0x27] = { "DAA", DAA, 0, 0, 0, 0, 0, 0, 1, 4},
[0x3F] = { "CCF", CCF, 0, 0, 0, 0, 0, 0, 1, 4, {_IGNORE, RESET, RESET, DEPENDENT} },
[0x37] = { "SCF", SCF, 0, 0, 0, 0, 0, 0, 1, 4, {_IGNORE, RESET, RESET, SET} },
[0x17] = { "RLA", RL, REGISTER, ADDR_MODE_NONE, A, OPERAND_NONE, 0, 0, 1, 4, {RESET, RESET, RESET, DEPENDENT} },
[0x1F] = { "RRA", RR, REGISTER, ADDR_MODE_NONE, A, OPERAND_NONE, 0, 0, 1, 4, {RESET, RESET, RESET, DEPENDENT}},
[0x07] = { "RLCA", RLC, REGISTER, ADDR_MODE_NONE, A, OPERAND_NONE, 0, 0, 1, 4, {RESET, RESET, RESET, DEPENDENT}},
[0x0F] = { "RRCA", RRC, REGISTER, ADDR_MODE_NONE, A, OPERAND_NONE, 0, 0, 1, 4, {RESET, RESET, RESET, DEPENDENT}},

[0xFB] = { "EI", EI, 0, 0, 0, 0, 0, 0, 1, 4},
[0xF3] = { "DI", DI, 0, 0, 0, 0, 0, 0, 1, 4},
};

Operation cb_operations[0x100] = {

	// RLC
	[0x07] = { "RLC A", RLC, REGISTER, ADDR_MODE_NONE, A, OPERAND_NONE, 0, 0, 2, 8, {DEPENDENT, RESET, RESET, DEPENDENT}},
	[0x00] = { "RLC B", RLC, REGISTER, ADDR_MODE_NONE, B, OPERAND_NONE, 0, 0, 2, 8, {DEPENDENT, RESET, RESET, DEPENDENT}},
	[0x01] = { "RLC C", RLC, REGISTER, ADDR_MODE_NONE, C, OPERAND_NONE, 0, 0, 2, 8, {DEPENDENT, RESET, RESET, DEPENDENT}},
	[0x02] = { "RLC D", RLC, REGISTER, ADDR_MODE_NONE, D, OPERAND_NONE, 0, 0, 2, 8, {DEPENDENT, RESET, RESET, DEPENDENT}},
	[0x03] = { "RLC E", RLC, REGISTER, ADDR_MODE_NONE, E, OPERAND_NONE, 0, 0, 2, 8, {DEPENDENT, RESET, RESET, DEPENDENT}},
	[0x04] = { "RLC H", RLC, REGISTER, ADDR_MODE_NONE, H, OPERAND_NONE, 0, 0, 2, 8, {DEPENDENT, RESET, RESET, DEPENDENT}},
	[0x05] = { "RLC L", RLC, REGISTER, ADDR_MODE_NONE, L, OPERAND_NONE, 0, 0, 2, 8, {DEPENDENT, RESET, RESET, DEPENDENT}},
	[0x06] = { "RLC (HL)", RLC, ADDRESS_R16, ADDR_MODE_NONE, HL, OPERAND_NONE, 0, 0, 2, 16, {DEPENDENT, RESET, RESET, DEPENDENT}},

	// RRC
	[0x0F] = { "RRC A", RRC, REGISTER, ADDR_MODE_NONE, A, OPERAND_NONE, 0, 0, 2, 8, {DEPENDENT, RESET, RESET, DEPENDENT}},
	[0x08] = { "RRC B", RRC, REGISTER, ADDR_MODE_NONE, B, OPERAND_NONE, 0, 0, 2, 8, {DEPENDENT, RESET, RESET, DEPENDENT}},
	[0x09] = { "RRC C", RRC, REGISTER, ADDR_MODE_NONE, C, OPERAND_NONE, 0, 0, 2, 8, {DEPENDENT, RESET, RESET, DEPENDENT}},
	[0x0A] = { "RRC D", RRC, REGISTER, ADDR_MODE_NONE, D, OPERAND_NONE, 0, 0, 2, 8, {DEPENDENT, RESET, RESET, DEPENDENT}},
	[0x0B] = { "RRC E", RRC, REGISTER, ADDR_MODE_NONE, E, OPERAND_NONE, 0, 0, 2, 8, {DEPENDENT, RESET, RESET, DEPENDENT}},
	[0x0C] = { "RRC H", RRC, REGISTER, ADDR_MODE_NONE, H, OPERAND_NONE, 0, 0, 2, 8, {DEPENDENT, RESET, RESET, DEPENDENT}},
	[0x0D] = { "RRC L", RRC, REGISTER, ADDR_MODE_NONE, L, OPERAND_NONE, 0, 0, 2, 8, {DEPENDENT, RESET, RESET, DEPENDENT}},
	[0x0E] = { "RRC (HL)", RRC, ADDRESS_R16, ADDR_MODE_NONE, HL, OPERAND_NONE, 0, 0, 2, 16, {DEPENDENT, RESET, RESET, DEPENDENT}},


	// RL
	[0x17] = {"RL A", RL, REGISTER, ADDR_MODE_NONE, A, OPERAND_NONE, 0, 0, 2, 8, {DEPENDENT, RESET, RESET, DEPENDENT}},
	[0x10] = {"RL B", RL, REGISTER, ADDR_MODE_NONE, B, OPERAND_NONE, 0, 0, 2, 8, {DEPENDENT, RESET, RESET, DEPENDENT}},
	[0x11] = {"RL C", RL, REGISTER, ADDR_MODE_NONE, C, OPERAND_NONE, 0, 0, 2, 8, {DEPENDENT, RESET, RESET, DEPENDENT}},
	[0x12] = {"RL D", RL, REGISTER, ADDR_MODE_NONE, D, OPERAND_NONE, 0, 0, 2, 8, {DEPENDENT, RESET, RESET, DEPENDENT}},
	[0x13] = {"RL E", RL, REGISTER, ADDR_MODE_NONE, E, OPERAND_NONE, 0, 0, 2, 8, {DEPENDENT, RESET, RESET, DEPENDENT}},
	[0x14] = {"RL H", RL, REGISTER, ADDR_MODE_NONE, H, OPERAND_NONE, 0, 0, 2, 8, {DEPENDENT, RESET, RESET, DEPENDENT}},
	[0x15] = {"RL L", RL, REGISTER, ADDR_MODE_NONE, L, OPERAND_NONE, 0, 0, 2, 8, {DEPENDENT, RESET, RESET, DEPENDENT}},
	[0x16] = { "RL (HL)", RL, ADDRESS_R16, ADDR_MODE_NONE, HL, OPERAND_NONE, 0, 0, 2, 16, {DEPENDENT, RESET, RESET, DEPENDENT}},

	[0x1F] = {"RR A", RR, REGISTER, ADDR_MODE_NONE, A, OPERAND_NONE, 0, 0, 2, 8, {DEPENDENT, RESET, RESET, DEPENDENT}},
	[0x18] = {"RR B", RR, REGISTER, ADDR_MODE_NONE, B, OPERAND_NONE, 0, 0, 2, 8, {DEPENDENT, RESET, RESET, DEPENDENT}},
	[0x19] = {"RR C", RR, REGISTER, ADDR_MODE_NONE, C, OPERAND_NONE, 0, 0, 2, 8, {DEPENDENT, RESET, RESET, DEPENDENT}},
	[0x1A] = {"RR D", RR, REGISTER, ADDR_MODE_NONE, D, OPERAND_NONE, 0, 0, 2, 8, {DEPENDENT, RESET, RESET, DEPENDENT}},
	[0x1B] = {"RR E", RR, REGISTER, ADDR_MODE_NONE, E, OPERAND_NONE, 0, 0, 2, 8, {DEPENDENT, RESET, RESET, DEPENDENT}},
	[0x1C] = {"RR H", RR, REGISTER, ADDR_MODE_NONE, H, OPERAND_NONE, 0, 0, 2, 8, {DEPENDENT, RESET, RESET, DEPENDENT}},
	[0x1D] = {"RR L", RR, REGISTER, ADDR_MODE_NONE, L, OPERAND_NONE, 0, 0, 2, 8, {DEPENDENT, RESET, RESET, DEPENDENT}},
	[0x1E] = { "RR (HL)", RR, ADDRESS_R16, ADDR_MODE_NONE, HL, OPERAND_NONE, 0, 0, 2, 16, {DEPENDENT, RESET, RESET, DEPENDENT}},

	// SLA
	[0x27] = {"SLA A", SLA, REGISTER, ADDR_MODE_NONE, A, OPERAND_NONE, 0, 0, 2, 8, {DEPENDENT, RESET, RESET, DEPENDENT}},
	[0x20] = {"SLA B", SLA, REGISTER, ADDR_MODE_NONE, B, OPERAND_NONE, 0, 0, 2, 8, {DEPENDENT, RESET, RESET, DEPENDENT}},
	[0x21] = {"SLA C", SLA, REGISTER, ADDR_MODE_NONE, C, OPERAND_NONE, 0, 0, 2, 8, {DEPENDENT, RESET, RESET, DEPENDENT}},
	[0x22] = {"SLA D", SLA, REGISTER, ADDR_MODE_NONE, D, OPERAND_NONE, 0, 0, 2, 8, {DEPENDENT, RESET, RESET, DEPENDENT}},
	[0x23] = {"SLA E", SLA, REGISTER, ADDR_MODE_NONE, E, OPERAND_NONE, 0, 0, 2, 8, {DEPENDENT, RESET, RESET, DEPENDENT}},
	[0x24] = {"SLA H", SLA, REGISTER, ADDR_MODE_NONE, H, OPERAND_NONE, 0, 0, 2, 8, {DEPENDENT, RESET, RESET, DEPENDENT}},
	[0x25] = {"SLA L", SLA, REGISTER, ADDR_MODE_NONE, L, OPERAND_NONE, 0, 0, 2, 8, {DEPENDENT, RESET, RESET, DEPENDENT}},
	[0x26] = {"SLA (HL)", SLA, ADDRESS_R16, ADDR_MODE_NONE, HL, OPERAND_NONE, 0, 0, 2, 16, {DEPENDENT, RESET, RESET, DEPENDENT}},

	// SRA
	[0x2F] = {"SRA A", SRA, REGISTER, ADDR_MODE_NONE, A, OPERAND_NONE, 0, 0, 2, 8, {DEPENDENT, RESET, RESET, DEPENDENT}},
	[0x28] = {"SRA B", SRA, REGISTER, ADDR_MODE_NONE, B, OPERAND_NONE, 0, 0, 2, 8, {DEPENDENT, RESET, RESET, DEPENDENT}},
	[0x29] = {"SRA C", SRA, REGISTER, ADDR_MODE_NONE, C, OPERAND_NONE, 0, 0, 2, 8, {DEPENDENT, RESET, RESET, DEPENDENT}},
	[0x2A] = {"SRA D", SRA, REGISTER, ADDR_MODE_NONE, D, OPERAND_NONE, 0, 0, 2, 8, {DEPENDENT, RESET, RESET, DEPENDENT}},
	[0x2B] = {"SRA E", SRA, REGISTER, ADDR_MODE_NONE, E, OPERAND_NONE, 0, 0, 2, 8, {DEPENDENT, RESET, RESET, DEPENDENT}},
	[0x2C] = {"SRA H", SRA, REGISTER, ADDR_MODE_NONE, H, OPERAND_NONE, 0, 0, 2, 8, {DEPENDENT, RESET, RESET, DEPENDENT}},
	[0x2D] = {"SRA L", SRA, REGISTER, ADDR_MODE_NONE, L, OPERAND_NONE, 0, 0, 2, 8, {DEPENDENT, RESET, RESET, DEPENDENT}},
	[0x2E] = {"SRA (HL)", SRA, ADDRESS_R16, ADDR_MODE_NONE, HL, OPERAND_NONE, 0, 0, 2, 16, {DEPENDENT, RESET, RESET, DEPENDENT}},

	// SWAP
	[0x37] = {"SWAP A", SWAP, REGISTER, ADDR_MODE_NONE, A, OPERAND_NONE, 0, 0, 2, 8, {DEPENDENT, RESET, RESET, RESET}},
	[0x30] = {"SWAP B", SWAP, REGISTER, ADDR_MODE_NONE, B, OPERAND_NONE, 0, 0, 2, 8, {DEPENDENT, RESET, RESET, RESET}},
	[0x31] = {"SWAP C", SWAP, REGISTER, ADDR_MODE_NONE, C, OPERAND_NONE, 0, 0, 2, 8, {DEPENDENT, RESET, RESET, RESET}},
	[0x32] = {"SWAP D", SWAP, REGISTER, ADDR_MODE_NONE, D, OPERAND_NONE, 0, 0, 2, 8, {DEPENDENT, RESET, RESET, RESET}},
	[0x33] = {"SWAP E", SWAP, REGISTER, ADDR_MODE_NONE, E, OPERAND_NONE, 0, 0, 2, 8, {DEPENDENT, RESET, RESET, RESET}},
	[0x34] = {"SWAP H", SWAP, REGISTER, ADDR_MODE_NONE, H, OPERAND_NONE, 0, 0, 2, 8, {DEPENDENT, RESET, RESET, RESET}},
	[0x35] = {"SWAP L", SWAP, REGISTER, ADDR_MODE_NONE, L, OPERAND_NONE, 0, 0, 2, 8, {DEPENDENT, RESET, RESET, RESET}},
	[0x36] = {"SWAP (HL)", SWAP, ADDRESS_R16, ADDR_MODE_NONE, HL, OPERAND_NONE, 0, 0, 2, 16, {DEPENDENT, RESET, RESET, RESET}},

	// SRL
	[0x3F] = {"SRL A", SRL, REGISTER, ADDR_MODE_NONE, A, OPERAND_NONE, 0, 0, 2, 8, {DEPENDENT, RESET, RESET, DEPENDENT}},
	[0x38] = {"SRL B", SRL, REGISTER, ADDR_MODE_NONE, B, OPERAND_NONE, 0, 0, 2, 8, {DEPENDENT, RESET, RESET, DEPENDENT}},
	[0x39] = {"SRL C", SRL, REGISTER, ADDR_MODE_NONE, C, OPERAND_NONE, 0, 0, 2, 8, {DEPENDENT, RESET, RESET, DEPENDENT}},
	[0x3A] = {"SRL D", SRL, REGISTER, ADDR_MODE_NONE, D, OPERAND_NONE, 0, 0, 2, 8, {DEPENDENT, RESET, RESET, DEPENDENT}},
	[0x3B] = {"SRL E", SRL, REGISTER, ADDR_MODE_NONE, E, OPERAND_NONE, 0, 0, 2, 8, {DEPENDENT, RESET, RESET, DEPENDENT}},
	[0x3C] = {"SRL H", SRL, REGISTER, ADDR_MODE_NONE, H, OPERAND_NONE, 0, 0, 2, 8, {DEPENDENT, RESET, RESET, DEPENDENT}},
	[0x3D] = {"SRL L", SRL, REGISTER, ADDR_MODE_NONE, L, OPERAND_NONE, 0, 0, 2, 8, {DEPENDENT, RESET, RESET, DEPENDENT}},
	[0x3E] = {"SRL (HL)", SRL, ADDRESS_R16, ADDR_MODE_NONE, HL, OPERAND_NONE, 0, 0, 2, 16, {DEPENDENT, RESET, RESET, DEPENDENT}},


	// BIT B, X // PUT THE BIT YOU ARE COMPARING INTO DEST AND REGISTER INTO SOURCE AND DONT ASK ANY QUESTIONS (if you think about it this actually makes more sense)	
	[0x47] = { "BIT 0, A", BIT, ADDR_MODE_NONE, REGISTER, 0, A, 0, 0, 2, 8, {DEPENDENT, RESET, SET, _IGNORE} },
	[0x40] = { "BIT 0, B", BIT, ADDR_MODE_NONE, REGISTER, 0, B, 0, 0, 2, 8, {DEPENDENT, RESET, SET, _IGNORE} },
	[0x41] = { "BIT 0, C", BIT, ADDR_MODE_NONE, REGISTER, 0, C, 0, 0, 2, 8, {DEPENDENT, RESET, SET, _IGNORE} },
	[0x42] = { "BIT 0, D", BIT, ADDR_MODE_NONE, REGISTER, 0, D, 0, 0, 2, 8, {DEPENDENT, RESET, SET, _IGNORE} },
	[0x43] = { "BIT 0, E", BIT, ADDR_MODE_NONE, REGISTER, 0, E, 0, 0, 2, 8, {DEPENDENT, RESET, SET, _IGNORE} },
	[0x44] = { "BIT 0, H", BIT, ADDR_MODE_NONE, REGISTER, 0, H, 0, 0, 2, 8, {DEPENDENT, RESET, SET, _IGNORE} },
	[0x45] = { "BIT 0, L", BIT, ADDR_MODE_NONE, REGISTER, 0, L, 0, 0, 2, 8, {DEPENDENT, RESET, SET, _IGNORE} },
	[0x46] = { "BIT 0, (HL)", BIT, ADDR_MODE_NONE, ADDRESS_R16, 0, HL, 0, 0, 2, 8, {DEPENDENT, RESET, SET, _IGNORE} },

	[0x4F] = { "BIT 1, A", BIT, ADDR_MODE_NONE, REGISTER, 1, A, 0, 0, 2, 8, {DEPENDENT, RESET, SET, _IGNORE} },
	[0x48] = { "BIT 1, B", BIT, ADDR_MODE_NONE, REGISTER, 1, B, 0, 0, 2, 8, {DEPENDENT, RESET, SET, _IGNORE} },
	[0x49] = { "BIT 1, C", BIT, ADDR_MODE_NONE, REGISTER, 1, C, 0, 0, 2, 8, {DEPENDENT, RESET, SET, _IGNORE} },
	[0x4A] = { "BIT 1, D", BIT, ADDR_MODE_NONE, REGISTER, 1, D, 0, 0, 2, 8, {DEPENDENT, RESET, SET, _IGNORE} },
	[0x4B] = { "BIT 1, E", BIT, ADDR_MODE_NONE, REGISTER, 1, E, 0, 0, 2, 8, {DEPENDENT, RESET, SET, _IGNORE} },
	[0x4C] = { "BIT 1, H", BIT, ADDR_MODE_NONE, REGISTER, 1, H, 0, 0, 2, 8, {DEPENDENT, RESET, SET, _IGNORE} },
	[0x4D] = { "BIT 1, L", BIT, ADDR_MODE_NONE, REGISTER, 1, L, 0, 0, 2, 8, {DEPENDENT, RESET, SET, _IGNORE} },
	[0x4E] = { "BIT 1, (HL)", BIT, ADDR_MODE_NONE, ADDRESS_R16, 1, HL, 0, 0, 2, 8, {DEPENDENT, RESET, SET, _IGNORE} },

	[0x57] = { "BIT 2, A", BIT, ADDR_MODE_NONE, REGISTER, 2, A, 0, 0, 2, 8, {DEPENDENT, RESET, SET, _IGNORE} },
	[0x50] = { "BIT 2, B", BIT, ADDR_MODE_NONE, REGISTER, 2, B, 0, 0, 2, 8, {DEPENDENT, RESET, SET, _IGNORE} },
	[0x51] = { "BIT 2, C", BIT, ADDR_MODE_NONE, REGISTER, 2, C, 0, 0, 2, 8, {DEPENDENT, RESET, SET, _IGNORE} },
	[0x52] = { "BIT 2, D", BIT, ADDR_MODE_NONE, REGISTER, 2, D, 0, 0, 2, 8, {DEPENDENT, RESET, SET, _IGNORE} },
	[0x53] = { "BIT 2, E", BIT, ADDR_MODE_NONE, REGISTER, 2, E, 0, 0, 2, 8, {DEPENDENT, RESET, SET, _IGNORE} },
	[0x54] = { "BIT 2, H", BIT, ADDR_MODE_NONE, REGISTER, 2, H, 0, 0, 2, 8, {DEPENDENT, RESET, SET, _IGNORE} },
	[0x55] = { "BIT 2, L", BIT, ADDR_MODE_NONE, REGISTER, 2, L, 0, 0, 2, 8, {DEPENDENT, RESET, SET, _IGNORE} },
	[0x56] = { "BIT 2, (HL)", BIT, ADDR_MODE_NONE, ADDRESS_R16, 2, HL, 0, 0, 2, 8, {DEPENDENT, RESET, SET, _IGNORE} },

	[0x5F] = { "BIT 3, A", BIT, ADDR_MODE_NONE, REGISTER, 3, A, 0, 0, 2, 8, {DEPENDENT, RESET, SET, _IGNORE} },[0x78] = { "BIT 7, B", BIT, ADDR_MODE_NONE, REGISTER, 7, B, 0, 0, 2, 8, {DEPENDENT, RESET, SET, _IGNORE} },
	[0x58] = { "BIT 3, B", BIT, ADDR_MODE_NONE, REGISTER, 3, B, 0, 0, 2, 8, {DEPENDENT, RESET, SET, _IGNORE} },
	[0x59] = { "BIT 3, C", BIT, ADDR_MODE_NONE, REGISTER, 3, C, 0, 0, 2, 8, {DEPENDENT, RESET, SET, _IGNORE} },
	[0x5A] = { "BIT 3, D", BIT, ADDR_MODE_NONE, REGISTER, 3, D, 0, 0, 2, 8, {DEPENDENT, RESET, SET, _IGNORE} },
	[0x5B] = { "BIT 3, E", BIT, ADDR_MODE_NONE, REGISTER, 3, E, 0, 0, 2, 8, {DEPENDENT, RESET, SET, _IGNORE} },
	[0x5C] = { "BIT 3, H", BIT, ADDR_MODE_NONE, REGISTER, 3, H, 0, 0, 2, 8, {DEPENDENT, RESET, SET, _IGNORE} },
	[0x5D] = { "BIT 3, L", BIT, ADDR_MODE_NONE, REGISTER, 3, L, 0, 0, 2, 8, {DEPENDENT, RESET, SET, _IGNORE} },
	[0x5E] = { "BIT 3, (HL)", BIT, ADDR_MODE_NONE, ADDRESS_R16, 3, HL, 0, 0, 2, 8, {DEPENDENT, RESET, SET, _IGNORE} },

	[0x67] = { "BIT 4, A", BIT, ADDR_MODE_NONE, REGISTER, 4, A, 0, 0, 2, 8, {DEPENDENT, RESET, SET, _IGNORE} },
	[0x60] = { "BIT 4, B", BIT, ADDR_MODE_NONE, REGISTER, 4, B, 0, 0, 2, 8, {DEPENDENT, RESET, SET, _IGNORE} },
	[0x61] = { "BIT 4, C", BIT, ADDR_MODE_NONE, REGISTER, 4, C, 0, 0, 2, 8, {DEPENDENT, RESET, SET, _IGNORE} },
	[0x62] = { "BIT 4, D", BIT, ADDR_MODE_NONE, REGISTER, 4, D, 0, 0, 2, 8, {DEPENDENT, RESET, SET, _IGNORE} },
	[0x63] = { "BIT 4, E", BIT, ADDR_MODE_NONE, REGISTER, 4, E, 0, 0, 2, 8, {DEPENDENT, RESET, SET, _IGNORE} },
	[0x64] = { "BIT 4, H", BIT, ADDR_MODE_NONE, REGISTER, 4, H, 0, 0, 2, 8, {DEPENDENT, RESET, SET, _IGNORE} },
	[0x65] = { "BIT 4, L", BIT, ADDR_MODE_NONE, REGISTER, 4, L, 0, 0, 2, 8, {DEPENDENT, RESET, SET, _IGNORE} },
	[0x66] = { "BIT 4, (HL)", BIT, ADDR_MODE_NONE, ADDRESS_R16, 4, HL, 0, 0, 2, 8, {DEPENDENT, RESET, SET, _IGNORE} },

	[0x6F] = { "BIT 5, A", BIT, ADDR_MODE_NONE, REGISTER, 5, A, 0, 0, 2, 8, {DEPENDENT, RESET, SET, _IGNORE} },[0x78] = { "BIT 7, B", BIT, ADDR_MODE_NONE, REGISTER, 7, B, 0, 0, 2, 8, {DEPENDENT, RESET, SET, _IGNORE} },
	[0x68] = { "BIT 5, B", BIT, ADDR_MODE_NONE, REGISTER, 5, B, 0, 0, 2, 8, {DEPENDENT, RESET, SET, _IGNORE} },
	[0x69] = { "BIT 5, C", BIT, ADDR_MODE_NONE, REGISTER, 5, C, 0, 0, 2, 8, {DEPENDENT, RESET, SET, _IGNORE} },
	[0x6A] = { "BIT 5, D", BIT, ADDR_MODE_NONE, REGISTER, 5, D, 0, 0, 2, 8, {DEPENDENT, RESET, SET, _IGNORE} },
	[0x6B] = { "BIT 5, E", BIT, ADDR_MODE_NONE, REGISTER, 5, E, 0, 0, 2, 8, {DEPENDENT, RESET, SET, _IGNORE} },
	[0x6C] = { "BIT 5, H", BIT, ADDR_MODE_NONE, REGISTER, 5, H, 0, 0, 2, 8, {DEPENDENT, RESET, SET, _IGNORE} },
	[0x6D] = { "BIT 5, L", BIT, ADDR_MODE_NONE, REGISTER, 5, L, 0, 0, 2, 8, {DEPENDENT, RESET, SET, _IGNORE} },
	[0x6E] = { "BIT 5, (HL)", BIT, ADDR_MODE_NONE, ADDRESS_R16, 5, HL, 0, 0, 2, 8, {DEPENDENT, RESET, SET, _IGNORE} },

	[0x77] = { "BIT 6, A", BIT, ADDR_MODE_NONE, REGISTER, 6, A, 0, 0, 2, 8, {DEPENDENT, RESET, SET, _IGNORE} },
	[0x70] = { "BIT 6, B", BIT, ADDR_MODE_NONE, REGISTER, 6, B, 0, 0, 2, 8, {DEPENDENT, RESET, SET, _IGNORE} },
	[0x71] = { "BIT 6, C", BIT, ADDR_MODE_NONE, REGISTER, 6, C, 0, 0, 2, 8, {DEPENDENT, RESET, SET, _IGNORE} },
	[0x72] = { "BIT 6, D", BIT, ADDR_MODE_NONE, REGISTER, 6, D, 0, 0, 2, 8, {DEPENDENT, RESET, SET, _IGNORE} },
	[0x73] = { "BIT 6, E", BIT, ADDR_MODE_NONE, REGISTER, 6, E, 0, 0, 2, 8, {DEPENDENT, RESET, SET, _IGNORE} },
	[0x74] = { "BIT 6, H", BIT, ADDR_MODE_NONE, REGISTER, 6, H, 0, 0, 2, 8, {DEPENDENT, RESET, SET, _IGNORE} },
	[0x75] = { "BIT 6, L", BIT, ADDR_MODE_NONE, REGISTER, 6, L, 0, 0, 2, 8, {DEPENDENT, RESET, SET, _IGNORE} },
	[0x76] = { "BIT 6, (HL)", BIT, ADDR_MODE_NONE, ADDRESS_R16, 6, HL, 0, 0, 2, 8, {DEPENDENT, RESET, SET, _IGNORE} },


	[0x7F] = { "BIT 7, A", BIT, ADDR_MODE_NONE, REGISTER, 7, A, 0, 0, 2, 8, {DEPENDENT, RESET, SET, _IGNORE} },
	[0x78] = { "BIT 7, B", BIT, ADDR_MODE_NONE, REGISTER, 7, B, 0, 0, 2, 8, {DEPENDENT, RESET, SET, _IGNORE} },
	[0x79] = { "BIT 7, C", BIT, ADDR_MODE_NONE, REGISTER, 7, C, 0, 0, 2, 8, {DEPENDENT, RESET, SET, _IGNORE} },
	[0x7A] = { "BIT 7, D", BIT, ADDR_MODE_NONE, REGISTER, 7, D, 0, 0, 2, 8, {DEPENDENT, RESET, SET, _IGNORE} },
	[0x7B] = { "BIT 7, E", BIT, ADDR_MODE_NONE, REGISTER, 7, E, 0, 0, 2, 8, {DEPENDENT, RESET, SET, _IGNORE} },
	[0x7C] = { "BIT 7, H", BIT, ADDR_MODE_NONE, REGISTER, 7, H, 0, 0, 2, 8, {DEPENDENT, RESET, SET, _IGNORE} },
	[0x7D] = { "BIT 7, L", BIT, ADDR_MODE_NONE, REGISTER, 7, L, 0, 0, 2, 8, {DEPENDENT, RESET, SET, _IGNORE} },
	[0x7E] = { "BIT 7, (HL)", BIT, ADDR_MODE_NONE, ADDRESS_R16, 7, HL, 0, 0, 2, 8, {DEPENDENT, RESET, SET, _IGNORE} },


	// RES
	[0x87] = {"RES 0, A", RES, REGISTER, ADDR_MODE_NONE, A, 0, 0, 0, 2, 8, {_IGNORE, _IGNORE, _IGNORE, _IGNORE}},
	[0x80] = {"RES 0, B", RES, REGISTER, ADDR_MODE_NONE, B, 0, 0, 0, 2, 8, {_IGNORE, _IGNORE, _IGNORE, _IGNORE}},
	[0x81] = {"RES 0, C", RES, REGISTER, ADDR_MODE_NONE, C, 0, 0, 0, 2, 8, {_IGNORE, _IGNORE, _IGNORE, _IGNORE}},
	[0x82] = {"RES 0, D", RES, REGISTER, ADDR_MODE_NONE, D, 0, 0, 0, 2, 8, {_IGNORE, _IGNORE, _IGNORE, _IGNORE}},
	[0x83] = {"RES 0, E", RES, REGISTER, ADDR_MODE_NONE, E, 0, 0, 0, 2, 8, {_IGNORE, _IGNORE, _IGNORE, _IGNORE}},
	[0x84] = {"RES 0, H", RES, REGISTER, ADDR_MODE_NONE, H, 0, 0, 0, 2, 8, {_IGNORE, _IGNORE, _IGNORE, _IGNORE}},
	[0x85] = {"RES 0, L", RES, REGISTER, ADDR_MODE_NONE, L, 0, 0, 0, 2, 8, {_IGNORE, _IGNORE, _IGNORE, _IGNORE}},
	[0x86] = {"RES 0, (HL)", RES, ADDRESS_R16, ADDR_MODE_NONE, HL, 0, 0, 0, 2, 16, {_IGNORE, _IGNORE, _IGNORE, _IGNORE}},

	[0x8F] = {"RES 1, A", RES, REGISTER, ADDR_MODE_NONE, A, 1, 0, 0, 2, 8, {_IGNORE, _IGNORE, _IGNORE, _IGNORE}},
	[0x88] = {"RES 1, B", RES, REGISTER, ADDR_MODE_NONE, B, 1, 0, 0, 2, 8, {_IGNORE, _IGNORE, _IGNORE, _IGNORE}},
	[0x89] = {"RES 1, C", RES, REGISTER, ADDR_MODE_NONE, C, 1, 0, 0, 2, 8, {_IGNORE, _IGNORE, _IGNORE, _IGNORE}},
	[0x8A] = {"RES 1, D", RES, REGISTER, ADDR_MODE_NONE, D, 1, 0, 0, 2, 8, {_IGNORE, _IGNORE, _IGNORE, _IGNORE}},
	[0x8B] = {"RES 1, E", RES, REGISTER, ADDR_MODE_NONE, E, 1, 0, 0, 2, 8, {_IGNORE, _IGNORE, _IGNORE, _IGNORE}},
	[0x8C] = {"RES 1, H", RES, REGISTER, ADDR_MODE_NONE, H, 1, 0, 0, 2, 8, {_IGNORE, _IGNORE, _IGNORE, _IGNORE}},
	[0x8D] = {"RES 1, L", RES, REGISTER, ADDR_MODE_NONE, L, 1, 0, 0, 2, 8, {_IGNORE, _IGNORE, _IGNORE, _IGNORE}},
	[0x8E] = {"RES 1, (HL)", RES, ADDRESS_R16, ADDR_MODE_NONE, HL, 1, 0, 0, 2, 16, {_IGNORE, _IGNORE, _IGNORE, _IGNORE}},

	[0x97] = {"RES 2, A", RES, REGISTER, ADDR_MODE_NONE, A, 2, 0, 0, 2, 8, {_IGNORE, _IGNORE, _IGNORE, _IGNORE}},
	[0x90] = {"RES 2, B", RES, REGISTER, ADDR_MODE_NONE, B, 2, 0, 0, 2, 8, {_IGNORE, _IGNORE, _IGNORE, _IGNORE}},
	[0x91] = {"RES 2, C", RES, REGISTER, ADDR_MODE_NONE, C, 2, 0, 0, 2, 8, {_IGNORE, _IGNORE, _IGNORE, _IGNORE}},
	[0x92] = {"RES 2, D", RES, REGISTER, ADDR_MODE_NONE, D, 2, 0, 0, 2, 8, {_IGNORE, _IGNORE, _IGNORE, _IGNORE}},
	[0x93] = {"RES 2, E", RES, REGISTER, ADDR_MODE_NONE, E, 2, 0, 0, 2, 8, {_IGNORE, _IGNORE, _IGNORE, _IGNORE}},
	[0x94] = {"RES 2, H", RES, REGISTER, ADDR_MODE_NONE, H, 2, 0, 0, 2, 8, {_IGNORE, _IGNORE, _IGNORE, _IGNORE}},
	[0x95] = {"RES 2, L", RES, REGISTER, ADDR_MODE_NONE, L, 2, 0, 0, 2, 8, {_IGNORE, _IGNORE, _IGNORE, _IGNORE}},
	[0x96] = {"RES 2, (HL)", RES, ADDRESS_R16, ADDR_MODE_NONE, HL, 2, 0, 0, 2, 16, {_IGNORE, _IGNORE, _IGNORE, _IGNORE}},

	[0x9F] = {"RES 3, A", RES, REGISTER, ADDR_MODE_NONE, A, 3, 0, 0, 2, 8, {_IGNORE, _IGNORE, _IGNORE, _IGNORE}},
	[0x98] = {"RES 3, B", RES, REGISTER, ADDR_MODE_NONE, B, 3, 0, 0, 2, 8, {_IGNORE, _IGNORE, _IGNORE, _IGNORE}},
	[0x99] = {"RES 3, C", RES, REGISTER, ADDR_MODE_NONE, C, 3, 0, 0, 2, 8, {_IGNORE, _IGNORE, _IGNORE, _IGNORE}},
	[0x9A] = {"RES 3, D", RES, REGISTER, ADDR_MODE_NONE, D, 3, 0, 0, 2, 8, {_IGNORE, _IGNORE, _IGNORE, _IGNORE}},
	[0x9B] = {"RES 3, E", RES, REGISTER, ADDR_MODE_NONE, E, 3, 0, 0, 2, 8, {_IGNORE, _IGNORE, _IGNORE, _IGNORE}},
	[0x9C] = {"RES 3, H", RES, REGISTER, ADDR_MODE_NONE, H, 3, 0, 0, 2, 8, {_IGNORE, _IGNORE, _IGNORE, _IGNORE}},
	[0x9D] = {"RES 3, L", RES, REGISTER, ADDR_MODE_NONE, L, 3, 0, 0, 2, 8, {_IGNORE, _IGNORE, _IGNORE, _IGNORE}},
	[0x9E] = {"RES 3, (HL)", RES, ADDRESS_R16, ADDR_MODE_NONE, HL, 3, 0, 0, 2, 16, {_IGNORE, _IGNORE, _IGNORE, _IGNORE}},

	[0xA7] = {"RES 4, A", RES, REGISTER, ADDR_MODE_NONE, A, 4, 0, 0, 2, 8, {_IGNORE, _IGNORE, _IGNORE, _IGNORE}},
	[0xA0] = {"RES 4, B", RES, REGISTER, ADDR_MODE_NONE, B, 4, 0, 0, 2, 8, {_IGNORE, _IGNORE, _IGNORE, _IGNORE}},
	[0xA1] = {"RES 4, C", RES, REGISTER, ADDR_MODE_NONE, C, 4, 0, 0, 2, 8, {_IGNORE, _IGNORE, _IGNORE, _IGNORE}},
	[0xA2] = {"RES 4, D", RES, REGISTER, ADDR_MODE_NONE, D, 4, 0, 0, 2, 8, {_IGNORE, _IGNORE, _IGNORE, _IGNORE}},
	[0xA3] = {"RES 4, E", RES, REGISTER, ADDR_MODE_NONE, E, 4, 0, 0, 2, 8, {_IGNORE, _IGNORE, _IGNORE, _IGNORE}},
	[0xA4] = {"RES 4, H", RES, REGISTER, ADDR_MODE_NONE, H, 4, 0, 0, 2, 8, {_IGNORE, _IGNORE, _IGNORE, _IGNORE}},
	[0xA5] = {"RES 4, L", RES, REGISTER, ADDR_MODE_NONE, L, 4, 0, 0, 2, 8, {_IGNORE, _IGNORE, _IGNORE, _IGNORE}},
	[0xA6] = {"RES 4, (HL)", RES, ADDRESS_R16, ADDR_MODE_NONE, HL, 4, 0, 0, 2, 16, {_IGNORE, _IGNORE, _IGNORE, _IGNORE}},

	[0xAF] = {"RES 5, A", RES, REGISTER, ADDR_MODE_NONE, A, 5, 0, 0, 2, 8, {_IGNORE, _IGNORE, _IGNORE, _IGNORE}},
	[0xA8] = {"RES 5, B", RES, REGISTER, ADDR_MODE_NONE, B, 5, 0, 0, 2, 8, {_IGNORE, _IGNORE, _IGNORE, _IGNORE}},
	[0xA9] = {"RES 5, C", RES, REGISTER, ADDR_MODE_NONE, C, 5, 0, 0, 2, 8, {_IGNORE, _IGNORE, _IGNORE, _IGNORE}},
	[0xAA] = {"RES 5, D", RES, REGISTER, ADDR_MODE_NONE, D, 5, 0, 0, 2, 8, {_IGNORE, _IGNORE, _IGNORE, _IGNORE}},
	[0xAB] = {"RES 5, E", RES, REGISTER, ADDR_MODE_NONE, E, 5, 0, 0, 2, 8, {_IGNORE, _IGNORE, _IGNORE, _IGNORE}},
	[0xAC] = {"RES 5, H", RES, REGISTER, ADDR_MODE_NONE, H, 5, 0, 0, 2, 8, {_IGNORE, _IGNORE, _IGNORE, _IGNORE}},
	[0xAD] = {"RES 5, L", RES, REGISTER, ADDR_MODE_NONE, L, 5, 0, 0, 2, 8, {_IGNORE, _IGNORE, _IGNORE, _IGNORE}},
	[0xAE] = {"RES 5, (HL)", RES, ADDRESS_R16, ADDR_MODE_NONE, HL, 5, 0, 0, 2, 16, {_IGNORE, _IGNORE, _IGNORE, _IGNORE}},

	[0xB7] = {"RES 6, A", RES, REGISTER, ADDR_MODE_NONE, A, 6, 0, 0, 2, 8, {_IGNORE, _IGNORE, _IGNORE, _IGNORE}},
	[0xB0] = {"RES 6, B", RES, REGISTER, ADDR_MODE_NONE, B, 6, 0, 0, 2, 8, {_IGNORE, _IGNORE, _IGNORE, _IGNORE}},
	[0xB1] = {"RES 6, C", RES, REGISTER, ADDR_MODE_NONE, C, 6, 0, 0, 2, 8, {_IGNORE, _IGNORE, _IGNORE, _IGNORE}},
	[0xB2] = {"RES 6, D", RES, REGISTER, ADDR_MODE_NONE, D, 6, 0, 0, 2, 8, {_IGNORE, _IGNORE, _IGNORE, _IGNORE}},
	[0xB3] = {"RES 6, E", RES, REGISTER, ADDR_MODE_NONE, E, 6, 0, 0, 2, 8, {_IGNORE, _IGNORE, _IGNORE, _IGNORE}},
	[0xB4] = {"RES 6, H", RES, REGISTER, ADDR_MODE_NONE, H, 6, 0, 0, 2, 8, {_IGNORE, _IGNORE, _IGNORE, _IGNORE}},
	[0xB5] = {"RES 6, L", RES, REGISTER, ADDR_MODE_NONE, L, 6, 0, 0, 2, 8, {_IGNORE, _IGNORE, _IGNORE, _IGNORE}},
	[0xB6] = {"RES 6, (HL)", RES, ADDRESS_R16, ADDR_MODE_NONE, HL, 6, 0, 0, 2, 16, {_IGNORE, _IGNORE, _IGNORE, _IGNORE}},

	[0xBF] = {"RES 7, A", RES, REGISTER, ADDR_MODE_NONE, A, 7, 0, 0, 2, 8, {_IGNORE, _IGNORE, _IGNORE, _IGNORE}},
	[0xB8] = {"RES 7, B", RES, REGISTER, ADDR_MODE_NONE, B, 7, 0, 0, 2, 8, {_IGNORE, _IGNORE, _IGNORE, _IGNORE}},
	[0xB9] = {"RES 7, C", RES, REGISTER, ADDR_MODE_NONE, C, 7, 0, 0, 2, 8, {_IGNORE, _IGNORE, _IGNORE, _IGNORE}},
	[0xBA] = {"RES 7, D", RES, REGISTER, ADDR_MODE_NONE, D, 7, 0, 0, 2, 8, {_IGNORE, _IGNORE, _IGNORE, _IGNORE}},
	[0xBB] = {"RES 7, E", RES, REGISTER, ADDR_MODE_NONE, E, 7, 0, 0, 2, 8, {_IGNORE, _IGNORE, _IGNORE, _IGNORE}},
	[0xBC] = {"RES 7, H", RES, REGISTER, ADDR_MODE_NONE, H, 7, 0, 0, 2, 8, {_IGNORE, _IGNORE, _IGNORE, _IGNORE}},
	[0xBD] = {"RES 7, L", RES, REGISTER, ADDR_MODE_NONE, L, 7, 0, 0, 2, 8, {_IGNORE, _IGNORE, _IGNORE, _IGNORE}},
	[0xBE] = {"RES 7, (HL)", RES, ADDRESS_R16, ADDR_MODE_NONE, HL, 7, 0, 0, 2, 16, {_IGNORE, _IGNORE, _IGNORE, _IGNORE}},

	// SET

	[0xC7] = {"SET 0, A", SET_OP, REGISTER, ADDR_MODE_NONE, A, 0, 0, 0, 2, 8 },
	[0xC0] = {"SET 0, B", SET_OP, REGISTER, ADDR_MODE_NONE, B, 0, 0, 0, 2, 8 },
	[0xC1] = {"SET 0, C", SET_OP, REGISTER, ADDR_MODE_NONE, C, 0, 0, 0, 2, 8 },
	[0xC2] = {"SET 0, D", SET_OP, REGISTER, ADDR_MODE_NONE, D, 0, 0, 0, 2, 8 },
	[0xC3] = {"SET 0, E", SET_OP, REGISTER, ADDR_MODE_NONE, E, 0, 0, 0, 2, 8 },
	[0xC4] = {"SET 0, H", SET_OP, REGISTER, ADDR_MODE_NONE, H, 0, 0, 0, 2, 8 },
	[0xC5] = {"SET 0, L", SET_OP, REGISTER, ADDR_MODE_NONE, L, 0, 0, 0, 2, 8 },
	[0xC6] = {"SET 0, (HL)", SET_OP, ADDRESS_R16, ADDR_MODE_NONE, HL, 0, 0, 0, 2, 16, },

	[0xCF] = {"SET 1, A", SET_OP, REGISTER, ADDR_MODE_NONE, A, 1, 0, 0, 2, 8 },
	[0xC8] = {"SET 1, B", SET_OP, REGISTER, ADDR_MODE_NONE, B, 1, 0, 0, 2, 8 },
	[0xC9] = {"SET 1, C", SET_OP, REGISTER, ADDR_MODE_NONE, C, 1, 0, 0, 2, 8 },
	[0xCA] = {"SET 1, D", SET_OP, REGISTER, ADDR_MODE_NONE, D, 1, 0, 0, 2, 8 },
	[0xCB] = {"SET 1, E", SET_OP, REGISTER, ADDR_MODE_NONE, E, 1, 0, 0, 2, 8 },
	[0xCC] = {"SET 1, H", SET_OP, REGISTER, ADDR_MODE_NONE, H, 1, 0, 0, 2, 8 },
	[0xCD] = {"SET 1, L", SET_OP, REGISTER, ADDR_MODE_NONE, L, 1, 0, 0, 2, 8 },
	[0xCE] = {"SET 1, (HL)", SET_OP, ADDRESS_R16, ADDR_MODE_NONE, HL, 1, 0, 0, 2, 16, },

	[0xD7] = {"SET 2, A", SET_OP, REGISTER, ADDR_MODE_NONE, A, 2, 0, 0, 2, 8 },
	[0xD0] = {"SET 2, B", SET_OP, REGISTER, ADDR_MODE_NONE, B, 2, 0, 0, 2, 8 },
	[0xD1] = {"SET 2, C", SET_OP, REGISTER, ADDR_MODE_NONE, C, 2, 0, 0, 2, 8 },
	[0xD2] = {"SET 2, D", SET_OP, REGISTER, ADDR_MODE_NONE, D, 2, 0, 0, 2, 8 },
	[0xD3] = {"SET 2, E", SET_OP, REGISTER, ADDR_MODE_NONE, E, 2, 0, 0, 2, 8 },
	[0xD4] = {"SET 2, H", SET_OP, REGISTER, ADDR_MODE_NONE, H, 2, 0, 0, 2, 8 },
	[0xD5] = {"SET 2, L", SET_OP, REGISTER, ADDR_MODE_NONE, L, 2, 0, 0, 2, 8 },
	[0xD6] = {"SET 2, (HL)", SET_OP, ADDRESS_R16, ADDR_MODE_NONE, HL, 2, 0, 0, 2, 16, },

	[0xDF] = {"SET 3, A", SET_OP, REGISTER, ADDR_MODE_NONE, A, 3, 0, 0, 2, 8 },
	[0xD8] = {"SET 3, B", SET_OP, REGISTER, ADDR_MODE_NONE, B, 3, 0, 0, 2, 8 },
	[0xD9] = {"SET 3, C", SET_OP, REGISTER, ADDR_MODE_NONE, C, 3, 0, 0, 2, 8 },
	[0xDA] = {"SET 3, D", SET_OP, REGISTER, ADDR_MODE_NONE, D, 3, 0, 0, 2, 8 },
	[0xDB] = {"SET 3, E", SET_OP, REGISTER, ADDR_MODE_NONE, E, 3, 0, 0, 2, 8 },
	[0xDC] = {"SET 3, H", SET_OP, REGISTER, ADDR_MODE_NONE, H, 3, 0, 0, 2, 8 },
	[0xDD] = {"SET 3, L", SET_OP, REGISTER, ADDR_MODE_NONE, L, 3, 0, 0, 2, 8 },
	[0xDE] = {"SET 3, (HL)", SET_OP, ADDRESS_R16, ADDR_MODE_NONE, HL, 3, 0, 0, 2, 16, },

	[0xE7] = {"SET 4, A", SET_OP, REGISTER, ADDR_MODE_NONE, A, 4, 0, 0, 2, 8 },
	[0xE0] = {"SET 4, B", SET_OP, REGISTER, ADDR_MODE_NONE, B, 4, 0, 0, 2, 8 },
	[0xE1] = {"SET 4, C", SET_OP, REGISTER, ADDR_MODE_NONE, C, 4, 0, 0, 2, 8 },
	[0xE2] = {"SET 4, D", SET_OP, REGISTER, ADDR_MODE_NONE, D, 4, 0, 0, 2, 8 },
	[0xE3] = {"SET 4, E", SET_OP, REGISTER, ADDR_MODE_NONE, E, 4, 0, 0, 2, 8 },
	[0xE4] = {"SET 4, H", SET_OP, REGISTER, ADDR_MODE_NONE, H, 4, 0, 0, 2, 8 },
	[0xE5] = {"SET 4, L", SET_OP, REGISTER, ADDR_MODE_NONE, L, 4, 0, 0, 2, 8 },
	[0xE6] = {"SET 4, (HL)", SET_OP, ADDRESS_R16, ADDR_MODE_NONE, HL, 4, 0, 0, 2, 16, },

	[0xEF] = {"SET 5, A", SET_OP, REGISTER, ADDR_MODE_NONE, A, 5, 0, 0, 2, 8 },
	[0xE8] = {"SET 5, B", SET_OP, REGISTER, ADDR_MODE_NONE, B, 5, 0, 0, 2, 8 },
	[0xE9] = {"SET 5, C", SET_OP, REGISTER, ADDR_MODE_NONE, C, 5, 0, 0, 2, 8 },
	[0xEA] = {"SET 5, D", SET_OP, REGISTER, ADDR_MODE_NONE, D, 5, 0, 0, 2, 8 },
	[0xEB] = {"SET 5, E", SET_OP, REGISTER, ADDR_MODE_NONE, E, 5, 0, 0, 2, 8 },
	[0xEC] = {"SET 5, H", SET_OP, REGISTER, ADDR_MODE_NONE, H, 5, 0, 0, 2, 8 },
	[0xED] = {"SET 5, L", SET_OP, REGISTER, ADDR_MODE_NONE, L, 5, 0, 0, 2, 8 },
	[0xEE] = {"SET 5, (HL)", SET_OP, ADDRESS_R16, ADDR_MODE_NONE, HL, 5, 0, 0, 2, 16, },

	[0xF7] = {"SET 6, A", SET_OP, REGISTER, ADDR_MODE_NONE, A, 6, 0, 0, 2, 8 },
	[0xF0] = {"SET 6, B", SET_OP, REGISTER, ADDR_MODE_NONE, B, 6, 0, 0, 2, 8 },
	[0xF1] = {"SET 6, C", SET_OP, REGISTER, ADDR_MODE_NONE, C, 6, 0, 0, 2, 8 },
	[0xF2] = {"SET 6, D", SET_OP, REGISTER, ADDR_MODE_NONE, D, 6, 0, 0, 2, 8 },
	[0xF3] = {"SET 6, E", SET_OP, REGISTER, ADDR_MODE_NONE, E, 6, 0, 0, 2, 8 },
	[0xF4] = {"SET 6, H", SET_OP, REGISTER, ADDR_MODE_NONE, H, 6, 0, 0, 2, 8 },
	[0xF5] = {"SET 6, L", SET_OP, REGISTER, ADDR_MODE_NONE, L, 6, 0, 0, 2, 8 },
	[0xF6] = {"SET 6, (HL)", SET_OP, ADDRESS_R16, ADDR_MODE_NONE, HL, 6, 0, 0, 2, 16, },

	[0xFF] = {"SET 7, A", SET_OP, REGISTER, ADDR_MODE_NONE, A, 7, 0, 0, 2, 8 },
	[0xF8] = {"SET 7, B", SET_OP, REGISTER, ADDR_MODE_NONE, B, 7, 0, 0, 2, 8 },
	[0xF9] = {"SET 7, C", SET_OP, REGISTER, ADDR_MODE_NONE, C, 7, 0, 0, 2, 8 },
	[0xFA] = {"SET 7, D", SET_OP, REGISTER, ADDR_MODE_NONE, D, 7, 0, 0, 2, 8 },
	[0xFB] = {"SET 7, E", SET_OP, REGISTER, ADDR_MODE_NONE, E, 7, 0, 0, 2, 8 },
	[0xFC] = {"SET 7, H", SET_OP, REGISTER, ADDR_MODE_NONE, H, 7, 0, 0, 2, 8 },
	[0xFD] = {"SET 7, L", SET_OP, REGISTER, ADDR_MODE_NONE, L, 7, 0, 0, 2, 8 },
	[0xFE] = {"SET 7, (HL)", SET_OP, ADDRESS_R16, ADDR_MODE_NONE, HL, 7, 0, 0, 2, 16, },
};
